// Code generated by protoc-gen-go-defaults. DO NOT EDIT.

package testpb

import (
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

func (x *Test) SetDefaults() {
	if x.StringField == "" {
		x.StringField = "string_field"
	}
	if x.NumberField == 0 {
		x.NumberField = 42
	}
	if x.BoolField == false {
		x.BoolField = true
	}
	if x.EnumField == 0 {
		x.EnumField = 2
	}
	if v, ok := interface{}(x.MessageField).(interface{ SetDefaults() }); ok && x.MessageField != nil {
		v.SetDefaults()
	}
	if x.NumberValueField == nil {
		x.NumberValueField = &wrapperspb.Int64Value{Value: 43}
	}
	if x.StringValueField == nil {
		x.StringValueField = &wrapperspb.StringValue{Value: "string_value"}
	}
	if x.BoolValueField == nil {
		x.BoolValueField = &wrapperspb.BoolValue{Value: false}
	}
	if x.TimeValueField == nil {
		x.TimeValueField = timestamppb.Now()
	}
	if x.DurationValueField == nil {
		x.DurationValueField = durationpb.New(25401600000000000)
	}
	if x.Oneof == nil {
		x.Oneof = &Test_Two{}
	}
	switch x := x.Oneof.(type) {
	case *Test_One:
		if x.One == nil {
			x.One = &OneOfOne{}
		}
		if v, ok := interface{}(x.One).(interface{ SetDefaults() }); ok && x.One != nil {
			v.SetDefaults()
		}
	case *Test_Two:
		if x.Two == nil {
			x.Two = &OneOfTwo{}
		}
		if v, ok := interface{}(x.Two).(interface{ SetDefaults() }); ok && x.Two != nil {
			v.SetDefaults()
		}
	case *Test_Three:
		if x.Three == nil {
			x.Three = &OneOfThree{}
		}
		if v, ok := interface{}(x.Three).(interface{ SetDefaults() }); ok && x.Three != nil {
			v.SetDefaults()
		}
	case *Test_Four:
		if x.Four == 0 {
			x.Four = 1
		}
	}
	if x.Descriptor_ == nil {
		x.Descriptor_ = &descriptorpb.DescriptorProto{}
	}
	if v, ok := interface{}(x.Descriptor_).(interface{ SetDefaults() }); ok && x.Descriptor_ != nil {
		v.SetDefaults()
	}
	if x.TimeValueFieldWithDefault == nil {
		x.TimeValueFieldWithDefault = &timestamppb.Timestamp{Seconds: -562032000, Nanos: 0}
	}
	if len(x.Bytes) == 0 {
		x.Bytes = []byte("??")
	}
}

func (x *TestOptional) SetDefaults() {
	if x.StringField == nil {
		v := string("string_field")
		x.StringField = &v
	}
	if x.NumberField == nil {
		v := int64(42)
		x.NumberField = &v
	}
	if x.BoolField == nil {
		v := bool(true)
		x.BoolField = &v
	}
	if x.EnumField == nil {
		v := TestOptional_Type(2)
		x.EnumField = &v
	}
}

func (x *TestUnexported) _SetDefaults() {
	if x.StringField == nil {
		v := string("string_field")
		x.StringField = &v
	}
	if x.NumberField == nil {
		v := int64(42)
		x.NumberField = &v
	}
	if x.BoolField == nil {
		v := bool(true)
		x.BoolField = &v
	}
	if x.EnumField == nil {
		v := TestUnexported_Type(2)
		x.EnumField = &v
	}
}
