// Copyright 2021 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/generator/testpb/types.proto

package testpb

import (
	_ "github.com/protoc-contrib/protoc-gen-go-defaults/defaults"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Complex Field Types
type Types_Enum int32

const (
	Types_NONE Types_Enum = 0
	Types_ONE  Types_Enum = 1
	Types_TWO  Types_Enum = 2
)

// Enum value maps for Types_Enum.
var (
	Types_Enum_name = map[int32]string{
		0: "NONE",
		1: "ONE",
		2: "TWO",
	}
	Types_Enum_value = map[string]int32{
		"NONE": 0,
		"ONE":  1,
		"TWO":  2,
	}
)

func (x Types_Enum) Enum() *Types_Enum {
	p := new(Types_Enum)
	*p = x
	return p
}

func (x Types_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Types_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_generator_testpb_types_proto_enumTypes[0].Descriptor()
}

func (Types_Enum) Type() protoreflect.EnumType {
	return &file_internal_generator_testpb_types_proto_enumTypes[0]
}

func (x Types_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Types_Enum.Descriptor instead.
func (Types_Enum) EnumDescriptor() ([]byte, []int) {
	return file_internal_generator_testpb_types_proto_rawDescGZIP(), []int{0, 0}
}

type Types struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scalar Field Types
	Float    float32    `protobuf:"fixed32,1,opt,name=float,proto3" json:"float,omitempty"`
	Double   float64    `protobuf:"fixed64,2,opt,name=double,proto3" json:"double,omitempty"`
	Int32    int32      `protobuf:"varint,3,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64    int64      `protobuf:"varint,4,opt,name=int64,proto3" json:"int64,omitempty"`
	Uint32   uint32     `protobuf:"varint,5,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64   uint64     `protobuf:"varint,6,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Sint32   int32      `protobuf:"zigzag32,7,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64   int64      `protobuf:"zigzag64,8,opt,name=sint64,proto3" json:"sint64,omitempty"`
	Fixed32  uint32     `protobuf:"fixed32,9,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	Fixed64  uint64     `protobuf:"fixed64,10,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	Sfixed32 int32      `protobuf:"fixed32,11,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	Sfixed64 int64      `protobuf:"fixed64,12,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Bool     bool       `protobuf:"varint,13,opt,name=bool,proto3" json:"bool,omitempty"`
	String_  string     `protobuf:"bytes,14,opt,name=string,proto3" json:"string,omitempty"`
	Bytes    []byte     `protobuf:"bytes,15,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Enum     Types_Enum `protobuf:"varint,16,opt,name=enum,proto3,enum=tests.Types_Enum" json:"enum,omitempty"`
	Message  *Message   `protobuf:"bytes,17,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Oneof:
	//
	//	*Types_One
	//	*Types_Two
	//	*Types_Three
	//	*Types_Four
	Oneof isTypes_Oneof `protobuf_oneof:"oneof"`
	// WellKnow types
	Duration      *durationpb.Duration    `protobuf:"bytes,18,opt,name=duration,proto3" json:"duration,omitempty"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,19,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DoubleValue   *wrapperspb.DoubleValue `protobuf:"bytes,20,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	FloatValue    *wrapperspb.FloatValue  `protobuf:"bytes,21,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	Int64Value    *wrapperspb.Int64Value  `protobuf:"bytes,22,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint64Value   *wrapperspb.UInt64Value `protobuf:"bytes,23,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Int32Value    *wrapperspb.Int32Value  `protobuf:"bytes,24,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Uint32Value   *wrapperspb.UInt32Value `protobuf:"bytes,25,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	BoolValue     *wrapperspb.BoolValue   `protobuf:"bytes,26,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	StringValue   *wrapperspb.StringValue `protobuf:"bytes,27,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BytesValue    *wrapperspb.BytesValue  `protobuf:"bytes,28,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Types) Reset() {
	*x = Types{}
	mi := &file_internal_generator_testpb_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Types) ProtoMessage() {}

func (x *Types) ProtoReflect() protoreflect.Message {
	mi := &file_internal_generator_testpb_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Types.ProtoReflect.Descriptor instead.
func (*Types) Descriptor() ([]byte, []int) {
	return file_internal_generator_testpb_types_proto_rawDescGZIP(), []int{0}
}

func (x *Types) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *Types) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

func (x *Types) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *Types) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *Types) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *Types) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *Types) GetSint32() int32 {
	if x != nil {
		return x.Sint32
	}
	return 0
}

func (x *Types) GetSint64() int64 {
	if x != nil {
		return x.Sint64
	}
	return 0
}

func (x *Types) GetFixed32() uint32 {
	if x != nil {
		return x.Fixed32
	}
	return 0
}

func (x *Types) GetFixed64() uint64 {
	if x != nil {
		return x.Fixed64
	}
	return 0
}

func (x *Types) GetSfixed32() int32 {
	if x != nil {
		return x.Sfixed32
	}
	return 0
}

func (x *Types) GetSfixed64() int64 {
	if x != nil {
		return x.Sfixed64
	}
	return 0
}

func (x *Types) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *Types) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *Types) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *Types) GetEnum() Types_Enum {
	if x != nil {
		return x.Enum
	}
	return Types_NONE
}

func (x *Types) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Types) GetOneof() isTypes_Oneof {
	if x != nil {
		return x.Oneof
	}
	return nil
}

func (x *Types) GetOne() *OneOfOne {
	if x != nil {
		if x, ok := x.Oneof.(*Types_One); ok {
			return x.One
		}
	}
	return nil
}

func (x *Types) GetTwo() *OneOfTwo {
	if x != nil {
		if x, ok := x.Oneof.(*Types_Two); ok {
			return x.Two
		}
	}
	return nil
}

func (x *Types) GetThree() *OneOfThree {
	if x != nil {
		if x, ok := x.Oneof.(*Types_Three); ok {
			return x.Three
		}
	}
	return nil
}

func (x *Types) GetFour() Types_Enum {
	if x != nil {
		if x, ok := x.Oneof.(*Types_Four); ok {
			return x.Four
		}
	}
	return Types_NONE
}

func (x *Types) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Types) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Types) GetDoubleValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DoubleValue
	}
	return nil
}

func (x *Types) GetFloatValue() *wrapperspb.FloatValue {
	if x != nil {
		return x.FloatValue
	}
	return nil
}

func (x *Types) GetInt64Value() *wrapperspb.Int64Value {
	if x != nil {
		return x.Int64Value
	}
	return nil
}

func (x *Types) GetUint64Value() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Uint64Value
	}
	return nil
}

func (x *Types) GetInt32Value() *wrapperspb.Int32Value {
	if x != nil {
		return x.Int32Value
	}
	return nil
}

func (x *Types) GetUint32Value() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Uint32Value
	}
	return nil
}

func (x *Types) GetBoolValue() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolValue
	}
	return nil
}

func (x *Types) GetStringValue() *wrapperspb.StringValue {
	if x != nil {
		return x.StringValue
	}
	return nil
}

func (x *Types) GetBytesValue() *wrapperspb.BytesValue {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

type isTypes_Oneof interface {
	isTypes_Oneof()
}

type Types_One struct {
	One *OneOfOne `protobuf:"bytes,29,opt,name=one,proto3,oneof"`
}

type Types_Two struct {
	Two *OneOfTwo `protobuf:"bytes,30,opt,name=two,proto3,oneof"`
}

type Types_Three struct {
	Three *OneOfThree `protobuf:"bytes,31,opt,name=three,proto3,oneof"`
}

type Types_Four struct {
	Four Types_Enum `protobuf:"varint,32,opt,name=four,proto3,enum=tests.Types_Enum,oneof"`
}

func (*Types_One) isTypes_Oneof() {}

func (*Types_Two) isTypes_Oneof() {}

func (*Types_Three) isTypes_Oneof() {}

func (*Types_Four) isTypes_Oneof() {}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_generator_testpb_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_generator_testpb_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_generator_testpb_types_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type OneOfOne struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StringField   string                 `protobuf:"bytes,1,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfOne) Reset() {
	*x = OneOfOne{}
	mi := &file_internal_generator_testpb_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfOne) ProtoMessage() {}

func (x *OneOfOne) ProtoReflect() protoreflect.Message {
	mi := &file_internal_generator_testpb_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfOne.ProtoReflect.Descriptor instead.
func (*OneOfOne) Descriptor() ([]byte, []int) {
	return file_internal_generator_testpb_types_proto_rawDescGZIP(), []int{2}
}

func (x *OneOfOne) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

type OneOfTwo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StringField   string                 `protobuf:"bytes,1,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfTwo) Reset() {
	*x = OneOfTwo{}
	mi := &file_internal_generator_testpb_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfTwo) ProtoMessage() {}

func (x *OneOfTwo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_generator_testpb_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfTwo.ProtoReflect.Descriptor instead.
func (*OneOfTwo) Descriptor() ([]byte, []int) {
	return file_internal_generator_testpb_types_proto_rawDescGZIP(), []int{3}
}

func (x *OneOfTwo) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

type OneOfThree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StringField   string                 `protobuf:"bytes,1,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfThree) Reset() {
	*x = OneOfThree{}
	mi := &file_internal_generator_testpb_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfThree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfThree) ProtoMessage() {}

func (x *OneOfThree) ProtoReflect() protoreflect.Message {
	mi := &file_internal_generator_testpb_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfThree.ProtoReflect.Descriptor instead.
func (*OneOfThree) Descriptor() ([]byte, []int) {
	return file_internal_generator_testpb_types_proto_rawDescGZIP(), []int{4}
}

func (x *OneOfThree) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

var File_internal_generator_testpb_types_proto protoreflect.FileDescriptor

const file_internal_generator_testpb_types_proto_rawDesc = "" +
	"\n" +
	"%internal/generator/testpb/types.proto\x12\x05tests\x1a\x17defaults/defaults.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x87\r\n" +
	"\x05Types\x12\x1f\n" +
	"\x05float\x18\x01 \x01(\x02B\t\xca\xed\x1a\x05\r=\n" +
	"\xd7>R\x05float\x12%\n" +
	"\x06double\x18\x02 \x01(\x01B\r\xca\xed\x1a\t\x11\xe1z\x14\xaeG\xe1\xda?R\x06double\x12\x1c\n" +
	"\x05int32\x18\x03 \x01(\x05B\x06\xca\xed\x1a\x02\x18*R\x05int32\x12\x1c\n" +
	"\x05int64\x18\x04 \x01(\x03B\x06\xca\xed\x1a\x02 *R\x05int64\x12\x1e\n" +
	"\x06uint32\x18\x05 \x01(\rB\x06\xca\xed\x1a\x02(*R\x06uint32\x12\x1e\n" +
	"\x06uint64\x18\x06 \x01(\x04B\x06\xca\xed\x1a\x020*R\x06uint64\x12\x1e\n" +
	"\x06sint32\x18\a \x01(\x11B\x06\xca\xed\x1a\x028TR\x06sint32\x12\x1e\n" +
	"\x06sint64\x18\b \x01(\x12B\x06\xca\xed\x1a\x02@TR\x06sint64\x12#\n" +
	"\afixed32\x18\t \x01(\aB\t\xca\xed\x1a\x05M*\x00\x00\x00R\afixed32\x12'\n" +
	"\afixed64\x18\n" +
	" \x01(\x06B\r\xca\xed\x1a\tQ*\x00\x00\x00\x00\x00\x00\x00R\afixed64\x12%\n" +
	"\bsfixed32\x18\v \x01(\x0fB\t\xca\xed\x1a\x05]*\x00\x00\x00R\bsfixed32\x12)\n" +
	"\bsfixed64\x18\f \x01(\x10B\r\xca\xed\x1a\ta*\x00\x00\x00\x00\x00\x00\x00R\bsfixed64\x12\x1a\n" +
	"\x04bool\x18\r \x01(\bB\x06\xca\xed\x1a\x02h\x01R\x04bool\x12 \n" +
	"\x06string\x18\x0e \x01(\tB\b\xca\xed\x1a\x04r\x0242R\x06string\x12\x1e\n" +
	"\x05bytes\x18\x0f \x01(\fB\b\xca\xed\x1a\x04z\x0242R\x05bytes\x12.\n" +
	"\x04enum\x18\x10 \x01(\x0e2\x11.tests.Types.EnumB\a\xca\xed\x1a\x03\x80\x01\x01R\x04enum\x123\n" +
	"\amessage\x18\x11 \x01(\v2\x0e.tests.MessageB\t\xca\xed\x1a\x05\x8a\x01\x02\b\x01R\amessage\x120\n" +
	"\x03one\x18\x1d \x01(\v2\x0f.tests.OneOfOneB\v\xca\xed\x1a\a\x8a\x01\x04\b\x01\x10\x01H\x00R\x03one\x120\n" +
	"\x03two\x18\x1e \x01(\v2\x0f.tests.OneOfTwoB\v\xca\xed\x1a\a\x8a\x01\x04\b\x01\x10\x01H\x00R\x03two\x126\n" +
	"\x05three\x18\x1f \x01(\v2\x11.tests.OneOfThreeB\v\xca\xed\x1a\a\x8a\x01\x04\b\x01\x10\x01H\x00R\x05three\x120\n" +
	"\x04four\x18  \x01(\x0e2\x11.tests.Types.EnumB\a\xca\xed\x1a\x03\x80\x01\x01H\x00R\x04four\x12@\n" +
	"\bduration\x18\x12 \x01(\v2\x19.google.protobuf.DurationB\t\xca\xed\x1a\x05\xaa\x01\x022dR\bduration\x12D\n" +
	"\ttimestamp\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\xca\xed\x1a\x06\xb2\x01\x03nowR\ttimestamp\x12N\n" +
	"\fdouble_value\x18\x14 \x01(\v2\x1c.google.protobuf.DoubleValueB\r\xca\xed\x1a\t\x11\xe1z\x14\xaeG\xe1\xda?R\vdoubleValue\x12G\n" +
	"\vfloat_value\x18\x15 \x01(\v2\x1b.google.protobuf.FloatValueB\t\xca\xed\x1a\x05\r=\n" +
	"\xd7>R\n" +
	"floatValue\x12D\n" +
	"\vint64_value\x18\x16 \x01(\v2\x1b.google.protobuf.Int64ValueB\x06\xca\xed\x1a\x02 *R\n" +
	"int64Value\x12G\n" +
	"\fuint64_value\x18\x17 \x01(\v2\x1c.google.protobuf.UInt64ValueB\x06\xca\xed\x1a\x020*R\vuint64Value\x12D\n" +
	"\vint32_value\x18\x18 \x01(\v2\x1b.google.protobuf.Int32ValueB\x06\xca\xed\x1a\x02\x18*R\n" +
	"int32Value\x12G\n" +
	"\fuint32_value\x18\x19 \x01(\v2\x1c.google.protobuf.UInt32ValueB\x06\xca\xed\x1a\x02(*R\vuint32Value\x12A\n" +
	"\n" +
	"bool_value\x18\x1a \x01(\v2\x1a.google.protobuf.BoolValueB\x06\xca\xed\x1a\x02h\x00R\tboolValue\x12I\n" +
	"\fstring_value\x18\x1b \x01(\v2\x1c.google.protobuf.StringValueB\b\xca\xed\x1a\x04r\x0242R\vstringValue\x12F\n" +
	"\vbytes_value\x18\x1c \x01(\v2\x1b.google.protobuf.BytesValueB\b\xca\xed\x1a\x04z\x0242R\n" +
	"bytesValue\"\"\n" +
	"\x04Enum\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03ONE\x10\x01\x12\a\n" +
	"\x03TWO\x10\x02B\x10\n" +
	"\x05oneof\x12\a\xd2\xed\x1a\x03two\"3\n" +
	"\aMessage\x12(\n" +
	"\x05field\x18\x01 \x01(\tB\x12\xca\xed\x1a\x0er\flonely fieldR\x05field\"G\n" +
	"\bOneOfOne\x125\n" +
	"\fstring_field\x18\x01 \x01(\tB\x12\xca\xed\x1a\x0er\fstring_fieldR\vstringField:\x04\xd8\xed\x1a\x01\"A\n" +
	"\bOneOfTwo\x125\n" +
	"\fstring_field\x18\x01 \x01(\tB\x12\xca\xed\x1a\x0er\fstring_fieldR\vstringField\"C\n" +
	"\n" +
	"OneOfThree\x125\n" +
	"\fstring_field\x18\x01 \x01(\tB\x12\xca\xed\x1a\x0er\fstring_fieldR\vstringFieldBLZJgithub.com/protoc-contrib/protoc-gen-go-defaults/internal/generator/testpbb\x06proto3"

var (
	file_internal_generator_testpb_types_proto_rawDescOnce sync.Once
	file_internal_generator_testpb_types_proto_rawDescData []byte
)

func file_internal_generator_testpb_types_proto_rawDescGZIP() []byte {
	file_internal_generator_testpb_types_proto_rawDescOnce.Do(func() {
		file_internal_generator_testpb_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_generator_testpb_types_proto_rawDesc), len(file_internal_generator_testpb_types_proto_rawDesc)))
	})
	return file_internal_generator_testpb_types_proto_rawDescData
}

var file_internal_generator_testpb_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_generator_testpb_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_generator_testpb_types_proto_goTypes = []any{
	(Types_Enum)(0),                // 0: tests.Types.Enum
	(*Types)(nil),                  // 1: tests.Types
	(*Message)(nil),                // 2: tests.Message
	(*OneOfOne)(nil),               // 3: tests.OneOfOne
	(*OneOfTwo)(nil),               // 4: tests.OneOfTwo
	(*OneOfThree)(nil),             // 5: tests.OneOfThree
	(*durationpb.Duration)(nil),    // 6: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
	(*wrapperspb.DoubleValue)(nil), // 8: google.protobuf.DoubleValue
	(*wrapperspb.FloatValue)(nil),  // 9: google.protobuf.FloatValue
	(*wrapperspb.Int64Value)(nil),  // 10: google.protobuf.Int64Value
	(*wrapperspb.UInt64Value)(nil), // 11: google.protobuf.UInt64Value
	(*wrapperspb.Int32Value)(nil),  // 12: google.protobuf.Int32Value
	(*wrapperspb.UInt32Value)(nil), // 13: google.protobuf.UInt32Value
	(*wrapperspb.BoolValue)(nil),   // 14: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil), // 15: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 16: google.protobuf.BytesValue
}
var file_internal_generator_testpb_types_proto_depIdxs = []int32{
	0,  // 0: tests.Types.enum:type_name -> tests.Types.Enum
	2,  // 1: tests.Types.message:type_name -> tests.Message
	3,  // 2: tests.Types.one:type_name -> tests.OneOfOne
	4,  // 3: tests.Types.two:type_name -> tests.OneOfTwo
	5,  // 4: tests.Types.three:type_name -> tests.OneOfThree
	0,  // 5: tests.Types.four:type_name -> tests.Types.Enum
	6,  // 6: tests.Types.duration:type_name -> google.protobuf.Duration
	7,  // 7: tests.Types.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 8: tests.Types.double_value:type_name -> google.protobuf.DoubleValue
	9,  // 9: tests.Types.float_value:type_name -> google.protobuf.FloatValue
	10, // 10: tests.Types.int64_value:type_name -> google.protobuf.Int64Value
	11, // 11: tests.Types.uint64_value:type_name -> google.protobuf.UInt64Value
	12, // 12: tests.Types.int32_value:type_name -> google.protobuf.Int32Value
	13, // 13: tests.Types.uint32_value:type_name -> google.protobuf.UInt32Value
	14, // 14: tests.Types.bool_value:type_name -> google.protobuf.BoolValue
	15, // 15: tests.Types.string_value:type_name -> google.protobuf.StringValue
	16, // 16: tests.Types.bytes_value:type_name -> google.protobuf.BytesValue
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_generator_testpb_types_proto_init() }
func file_internal_generator_testpb_types_proto_init() {
	if File_internal_generator_testpb_types_proto != nil {
		return
	}
	file_internal_generator_testpb_types_proto_msgTypes[0].OneofWrappers = []any{
		(*Types_One)(nil),
		(*Types_Two)(nil),
		(*Types_Three)(nil),
		(*Types_Four)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_generator_testpb_types_proto_rawDesc), len(file_internal_generator_testpb_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_generator_testpb_types_proto_goTypes,
		DependencyIndexes: file_internal_generator_testpb_types_proto_depIdxs,
		EnumInfos:         file_internal_generator_testpb_types_proto_enumTypes,
		MessageInfos:      file_internal_generator_testpb_types_proto_msgTypes,
	}.Build()
	File_internal_generator_testpb_types_proto = out.File
	file_internal_generator_testpb_types_proto_goTypes = nil
	file_internal_generator_testpb_types_proto_depIdxs = nil
}
