// Copyright 2021 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protoc_contrib/defaults/options.proto

package defaults

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldDefaults encapsulates the default values for each type of field. Depending on the
// field, the correct set should be used to ensure proper defaults generation.
type FieldDefaults struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*FieldDefaults_Float
	//	*FieldDefaults_Double
	//	*FieldDefaults_Int32
	//	*FieldDefaults_Int64
	//	*FieldDefaults_Uint32
	//	*FieldDefaults_Uint64
	//	*FieldDefaults_Sint32
	//	*FieldDefaults_Sint64
	//	*FieldDefaults_Fixed32
	//	*FieldDefaults_Fixed64
	//	*FieldDefaults_Sfixed32
	//	*FieldDefaults_Sfixed64
	//	*FieldDefaults_Bool
	//	*FieldDefaults_String_
	//	*FieldDefaults_Bytes
	//	*FieldDefaults_Enum
	//	*FieldDefaults_Message
	//	*FieldDefaults_Duration
	//	*FieldDefaults_Timestamp
	//	*FieldDefaults_EnumName
	Type          isFieldDefaults_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDefaults) Reset() {
	*x = FieldDefaults{}
	mi := &file_protoc_contrib_defaults_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDefaults) ProtoMessage() {}

func (x *FieldDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_contrib_defaults_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDefaults.ProtoReflect.Descriptor instead.
func (*FieldDefaults) Descriptor() ([]byte, []int) {
	return file_protoc_contrib_defaults_options_proto_rawDescGZIP(), []int{0}
}

func (x *FieldDefaults) GetType() isFieldDefaults_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *FieldDefaults) GetFloat() float32 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Float); ok {
			return x.Float
		}
	}
	return 0
}

func (x *FieldDefaults) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Double); ok {
			return x.Double
		}
	}
	return 0
}

func (x *FieldDefaults) GetInt32() int32 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Int32); ok {
			return x.Int32
		}
	}
	return 0
}

func (x *FieldDefaults) GetInt64() int64 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Int64); ok {
			return x.Int64
		}
	}
	return 0
}

func (x *FieldDefaults) GetUint32() uint32 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Uint32); ok {
			return x.Uint32
		}
	}
	return 0
}

func (x *FieldDefaults) GetUint64() uint64 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Uint64); ok {
			return x.Uint64
		}
	}
	return 0
}

func (x *FieldDefaults) GetSint32() int32 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Sint32); ok {
			return x.Sint32
		}
	}
	return 0
}

func (x *FieldDefaults) GetSint64() int64 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Sint64); ok {
			return x.Sint64
		}
	}
	return 0
}

func (x *FieldDefaults) GetFixed32() uint32 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Fixed32); ok {
			return x.Fixed32
		}
	}
	return 0
}

func (x *FieldDefaults) GetFixed64() uint64 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Fixed64); ok {
			return x.Fixed64
		}
	}
	return 0
}

func (x *FieldDefaults) GetSfixed32() int32 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Sfixed32); ok {
			return x.Sfixed32
		}
	}
	return 0
}

func (x *FieldDefaults) GetSfixed64() int64 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Sfixed64); ok {
			return x.Sfixed64
		}
	}
	return 0
}

func (x *FieldDefaults) GetBool() bool {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *FieldDefaults) GetString_() string {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *FieldDefaults) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *FieldDefaults) GetEnum() uint32 {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Enum); ok {
			return x.Enum
		}
	}
	return 0
}

func (x *FieldDefaults) GetMessage() *MessageDefaults {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *FieldDefaults) GetDuration() string {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Duration); ok {
			return x.Duration
		}
	}
	return ""
}

func (x *FieldDefaults) GetTimestamp() string {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_Timestamp); ok {
			return x.Timestamp
		}
	}
	return ""
}

func (x *FieldDefaults) GetEnumName() string {
	if x != nil {
		if x, ok := x.Type.(*FieldDefaults_EnumName); ok {
			return x.EnumName
		}
	}
	return ""
}

type isFieldDefaults_Type interface {
	isFieldDefaults_Type()
}

type FieldDefaults_Float struct {
	// Scalar Field Types
	Float float32 `protobuf:"fixed32,1,opt,name=float,oneof"`
}

type FieldDefaults_Double struct {
	Double float64 `protobuf:"fixed64,2,opt,name=double,oneof"`
}

type FieldDefaults_Int32 struct {
	Int32 int32 `protobuf:"varint,3,opt,name=int32,oneof"`
}

type FieldDefaults_Int64 struct {
	Int64 int64 `protobuf:"varint,4,opt,name=int64,oneof"`
}

type FieldDefaults_Uint32 struct {
	Uint32 uint32 `protobuf:"varint,5,opt,name=uint32,oneof"`
}

type FieldDefaults_Uint64 struct {
	Uint64 uint64 `protobuf:"varint,6,opt,name=uint64,oneof"`
}

type FieldDefaults_Sint32 struct {
	Sint32 int32 `protobuf:"zigzag32,7,opt,name=sint32,oneof"`
}

type FieldDefaults_Sint64 struct {
	Sint64 int64 `protobuf:"zigzag64,8,opt,name=sint64,oneof"`
}

type FieldDefaults_Fixed32 struct {
	Fixed32 uint32 `protobuf:"fixed32,9,opt,name=fixed32,oneof"`
}

type FieldDefaults_Fixed64 struct {
	Fixed64 uint64 `protobuf:"fixed64,10,opt,name=fixed64,oneof"`
}

type FieldDefaults_Sfixed32 struct {
	Sfixed32 int32 `protobuf:"fixed32,11,opt,name=sfixed32,oneof"`
}

type FieldDefaults_Sfixed64 struct {
	Sfixed64 int64 `protobuf:"fixed64,12,opt,name=sfixed64,oneof"`
}

type FieldDefaults_Bool struct {
	Bool bool `protobuf:"varint,13,opt,name=bool,oneof"`
}

type FieldDefaults_String_ struct {
	String_ string `protobuf:"bytes,14,opt,name=string,oneof"`
}

type FieldDefaults_Bytes struct {
	Bytes []byte `protobuf:"bytes,15,opt,name=bytes,oneof"`
}

type FieldDefaults_Enum struct {
	// Complex Field Types
	Enum uint32 `protobuf:"varint,16,opt,name=enum,oneof"`
}

type FieldDefaults_Message struct {
	Message *MessageDefaults `protobuf:"bytes,17,opt,name=message,oneof"`
}

type FieldDefaults_Duration struct {
	// Well-Known Field Types
	// any       = 20;
	Duration string `protobuf:"bytes,21,opt,name=duration,oneof"`
}

type FieldDefaults_Timestamp struct {
	Timestamp string `protobuf:"bytes,22,opt,name=timestamp,oneof"`
}

type FieldDefaults_EnumName struct {
	// EnumName sets the default enum value by symbolic name. Prefer this
	// over `enum` when reordering would silently invalidate a numeric
	// default; unknown names fail loudly at generate time.
	EnumName string `protobuf:"bytes,23,opt,name=enum_name,json=enumName,oneof"`
}

func (*FieldDefaults_Float) isFieldDefaults_Type() {}

func (*FieldDefaults_Double) isFieldDefaults_Type() {}

func (*FieldDefaults_Int32) isFieldDefaults_Type() {}

func (*FieldDefaults_Int64) isFieldDefaults_Type() {}

func (*FieldDefaults_Uint32) isFieldDefaults_Type() {}

func (*FieldDefaults_Uint64) isFieldDefaults_Type() {}

func (*FieldDefaults_Sint32) isFieldDefaults_Type() {}

func (*FieldDefaults_Sint64) isFieldDefaults_Type() {}

func (*FieldDefaults_Fixed32) isFieldDefaults_Type() {}

func (*FieldDefaults_Fixed64) isFieldDefaults_Type() {}

func (*FieldDefaults_Sfixed32) isFieldDefaults_Type() {}

func (*FieldDefaults_Sfixed64) isFieldDefaults_Type() {}

func (*FieldDefaults_Bool) isFieldDefaults_Type() {}

func (*FieldDefaults_String_) isFieldDefaults_Type() {}

func (*FieldDefaults_Bytes) isFieldDefaults_Type() {}

func (*FieldDefaults_Enum) isFieldDefaults_Type() {}

func (*FieldDefaults_Message) isFieldDefaults_Type() {}

func (*FieldDefaults_Duration) isFieldDefaults_Type() {}

func (*FieldDefaults_Timestamp) isFieldDefaults_Type() {}

func (*FieldDefaults_EnumName) isFieldDefaults_Type() {}

// MessageDefaults define the default behaviour for this field.
type MessageDefaults struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Initialize specify that the message should be initialized
	Initialize *bool `protobuf:"varint,1,opt,name=initialize" json:"initialize,omitempty"`
	// Recurse specifies that the nested message's own SetDefaults() method
	// should be invoked after initialization.
	Recurse       *bool `protobuf:"varint,2,opt,name=recurse" json:"recurse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDefaults) Reset() {
	*x = MessageDefaults{}
	mi := &file_protoc_contrib_defaults_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDefaults) ProtoMessage() {}

func (x *MessageDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_contrib_defaults_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDefaults.ProtoReflect.Descriptor instead.
func (*MessageDefaults) Descriptor() ([]byte, []int) {
	return file_protoc_contrib_defaults_options_proto_rawDescGZIP(), []int{1}
}

func (x *MessageDefaults) GetInitialize() bool {
	if x != nil && x.Initialize != nil {
		return *x.Initialize
	}
	return false
}

func (x *MessageDefaults) GetRecurse() bool {
	if x != nil && x.Recurse != nil {
		return *x.Recurse
	}
	return false
}

var file_protoc_contrib_defaults_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         55003,
		Name:          "protoc_contrib.defaults.skip",
		Tag:           "varint,55003,opt,name=skip",
		Filename:      "protoc_contrib/defaults/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         55004,
		Name:          "protoc_contrib.defaults.unexported",
		Tag:           "varint,55004,opt,name=unexported",
		Filename:      "protoc_contrib/defaults/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         55002,
		Name:          "protoc_contrib.defaults.oneof",
		Tag:           "bytes,55002,opt,name=oneof",
		Filename:      "protoc_contrib/defaults/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldDefaults)(nil),
		Field:         55001,
		Name:          "protoc_contrib.defaults.value",
		Tag:           "bytes,55001,opt,name=value",
		Filename:      "protoc_contrib/defaults/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// Skip suppresses SetDefaults() generation for this message entirely,
	// so a caller can provide a hand-written method instead.
	//
	// optional bool skip = 55003;
	E_Skip = &file_protoc_contrib_defaults_options_proto_extTypes[0]
	// Unexported emits _SetDefaults() instead of SetDefaults(). Useful when
	// a caller wants to compose custom logic around the generated body by
	// writing a SetDefaults() that delegates to the generated method.
	//
	// optional bool unexported = 55004;
	E_Unexported = &file_protoc_contrib_defaults_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional string oneof = 55002;
	E_Oneof = &file_protoc_contrib_defaults_options_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Value specify the default value to set on this field. By default,
	// none is set on a field.
	//
	// optional protoc_contrib.defaults.FieldDefaults value = 55001;
	E_Value = &file_protoc_contrib_defaults_options_proto_extTypes[3]
)

var File_protoc_contrib_defaults_options_proto protoreflect.FileDescriptor

const file_protoc_contrib_defaults_options_proto_rawDesc = "" +
	"\n" +
	"%protoc_contrib/defaults/options.proto\x12\x17protoc_contrib.defaults\x1a google/protobuf/descriptor.proto\"\xe2\x04\n" +
	"\rFieldDefaults\x12\x16\n" +
	"\x05float\x18\x01 \x01(\x02H\x00R\x05float\x12\x18\n" +
	"\x06double\x18\x02 \x01(\x01H\x00R\x06double\x12\x16\n" +
	"\x05int32\x18\x03 \x01(\x05H\x00R\x05int32\x12\x16\n" +
	"\x05int64\x18\x04 \x01(\x03H\x00R\x05int64\x12\x18\n" +
	"\x06uint32\x18\x05 \x01(\rH\x00R\x06uint32\x12\x18\n" +
	"\x06uint64\x18\x06 \x01(\x04H\x00R\x06uint64\x12\x18\n" +
	"\x06sint32\x18\a \x01(\x11H\x00R\x06sint32\x12\x18\n" +
	"\x06sint64\x18\b \x01(\x12H\x00R\x06sint64\x12\x1a\n" +
	"\afixed32\x18\t \x01(\aH\x00R\afixed32\x12\x1a\n" +
	"\afixed64\x18\n" +
	" \x01(\x06H\x00R\afixed64\x12\x1c\n" +
	"\bsfixed32\x18\v \x01(\x0fH\x00R\bsfixed32\x12\x1c\n" +
	"\bsfixed64\x18\f \x01(\x10H\x00R\bsfixed64\x12\x14\n" +
	"\x04bool\x18\r \x01(\bH\x00R\x04bool\x12\x18\n" +
	"\x06string\x18\x0e \x01(\tH\x00R\x06string\x12\x16\n" +
	"\x05bytes\x18\x0f \x01(\fH\x00R\x05bytes\x12\x14\n" +
	"\x04enum\x18\x10 \x01(\rH\x00R\x04enum\x12D\n" +
	"\amessage\x18\x11 \x01(\v2(.protoc_contrib.defaults.MessageDefaultsH\x00R\amessage\x12\x1c\n" +
	"\bduration\x18\x15 \x01(\tH\x00R\bduration\x12\x1e\n" +
	"\ttimestamp\x18\x16 \x01(\tH\x00R\ttimestamp\x12\x1d\n" +
	"\tenum_name\x18\x17 \x01(\tH\x00R\benumName:\x04\xd8\xed\x1a\x01B\x06\n" +
	"\x04typeJ\x04\b\x12\x10\x15\"Q\n" +
	"\x0fMessageDefaults\x12\x1e\n" +
	"\n" +
	"initialize\x18\x01 \x01(\bR\n" +
	"initialize\x12\x18\n" +
	"\arecurse\x18\x02 \x01(\bR\arecurse:\x04\xd8\xed\x1a\x01:5\n" +
	"\x04skip\x12\x1f.google.protobuf.MessageOptions\x18ۭ\x03 \x01(\bR\x04skip:A\n" +
	"\n" +
	"unexported\x12\x1f.google.protobuf.MessageOptions\x18ܭ\x03 \x01(\bR\n" +
	"unexported:5\n" +
	"\x05oneof\x12\x1d.google.protobuf.OneofOptions\x18ڭ\x03 \x01(\tR\x05oneof:]\n" +
	"\x05value\x12\x1d.google.protobuf.FieldOptions\x18٭\x03 \x01(\v2&.protoc_contrib.defaults.FieldDefaultsR\x05valueBSZQgithub.com/protoc-contrib/protoc-gen-go-defaults/protoc_contrib/defaults;defaults"

var (
	file_protoc_contrib_defaults_options_proto_rawDescOnce sync.Once
	file_protoc_contrib_defaults_options_proto_rawDescData []byte
)

func file_protoc_contrib_defaults_options_proto_rawDescGZIP() []byte {
	file_protoc_contrib_defaults_options_proto_rawDescOnce.Do(func() {
		file_protoc_contrib_defaults_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoc_contrib_defaults_options_proto_rawDesc), len(file_protoc_contrib_defaults_options_proto_rawDesc)))
	})
	return file_protoc_contrib_defaults_options_proto_rawDescData
}

var file_protoc_contrib_defaults_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protoc_contrib_defaults_options_proto_goTypes = []any{
	(*FieldDefaults)(nil),               // 0: protoc_contrib.defaults.FieldDefaults
	(*MessageDefaults)(nil),             // 1: protoc_contrib.defaults.MessageDefaults
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
	(*descriptorpb.OneofOptions)(nil),   // 3: google.protobuf.OneofOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_protoc_contrib_defaults_options_proto_depIdxs = []int32{
	1, // 0: protoc_contrib.defaults.FieldDefaults.message:type_name -> protoc_contrib.defaults.MessageDefaults
	2, // 1: protoc_contrib.defaults.skip:extendee -> google.protobuf.MessageOptions
	2, // 2: protoc_contrib.defaults.unexported:extendee -> google.protobuf.MessageOptions
	3, // 3: protoc_contrib.defaults.oneof:extendee -> google.protobuf.OneofOptions
	4, // 4: protoc_contrib.defaults.value:extendee -> google.protobuf.FieldOptions
	0, // 5: protoc_contrib.defaults.value:type_name -> protoc_contrib.defaults.FieldDefaults
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	5, // [5:6] is the sub-list for extension type_name
	1, // [1:5] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoc_contrib_defaults_options_proto_init() }
func file_protoc_contrib_defaults_options_proto_init() {
	if File_protoc_contrib_defaults_options_proto != nil {
		return
	}
	file_protoc_contrib_defaults_options_proto_msgTypes[0].OneofWrappers = []any{
		(*FieldDefaults_Float)(nil),
		(*FieldDefaults_Double)(nil),
		(*FieldDefaults_Int32)(nil),
		(*FieldDefaults_Int64)(nil),
		(*FieldDefaults_Uint32)(nil),
		(*FieldDefaults_Uint64)(nil),
		(*FieldDefaults_Sint32)(nil),
		(*FieldDefaults_Sint64)(nil),
		(*FieldDefaults_Fixed32)(nil),
		(*FieldDefaults_Fixed64)(nil),
		(*FieldDefaults_Sfixed32)(nil),
		(*FieldDefaults_Sfixed64)(nil),
		(*FieldDefaults_Bool)(nil),
		(*FieldDefaults_String_)(nil),
		(*FieldDefaults_Bytes)(nil),
		(*FieldDefaults_Enum)(nil),
		(*FieldDefaults_Message)(nil),
		(*FieldDefaults_Duration)(nil),
		(*FieldDefaults_Timestamp)(nil),
		(*FieldDefaults_EnumName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_contrib_defaults_options_proto_rawDesc), len(file_protoc_contrib_defaults_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_protoc_contrib_defaults_options_proto_goTypes,
		DependencyIndexes: file_protoc_contrib_defaults_options_proto_depIdxs,
		MessageInfos:      file_protoc_contrib_defaults_options_proto_msgTypes,
		ExtensionInfos:    file_protoc_contrib_defaults_options_proto_extTypes,
	}.Build()
	File_protoc_contrib_defaults_options_proto = out.File
	file_protoc_contrib_defaults_options_proto_goTypes = nil
	file_protoc_contrib_defaults_options_proto_depIdxs = nil
}
