// Package generator emits Default() methods for proto messages annotated
// with the github.com/protoc-contrib/protoc-gen-go-defaults extensions.
package generator

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/protoc-contrib/protoc-gen-go-defaults/defaults"
)

const generatedFilenameSuffix = ".pb.defaults.go"

// Generate walks every proto file scheduled for generation and emits a
// *.pb.defaults.go companion containing the Default() methods.
func Generate(plugin *protogen.Plugin) error {
	for _, file := range plugin.Files {
		if !file.Generate {
			continue
		}
		if err := generateFile(plugin, file); err != nil {
			return err
		}
	}
	return nil
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) error {
	messages := collectMessages(file.Messages)
	if len(messages) == 0 {
		return nil
	}

	for _, msg := range messages {
		if err := check(msg); err != nil {
			return fmt.Errorf("%s: %w", msg.Desc.FullName(), err)
		}
	}

	emittable := make([]*protogen.Message, 0, len(messages))
	for _, msg := range messages {
		if messageIgnored(msg) {
			continue
		}
		emittable = append(emittable, msg)
	}
	if len(emittable) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + generatedFilenameSuffix
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-defaults. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, msg := range emittable {
		emitMessage(g, msg)
	}
	return nil
}

// collectMessages returns all messages in the file, including nested ones.
func collectMessages(msgs []*protogen.Message) []*protogen.Message {
	var out []*protogen.Message
	for _, m := range msgs {
		if m.Desc.IsMapEntry() {
			continue
		}
		out = append(out, m)
		out = append(out, collectMessages(m.Messages)...)
	}
	return out
}

func emitMessage(g *protogen.GeneratedFile, msg *protogen.Message) {
	method := "Default"
	if messageUnexported(msg) {
		method = "_Default"
	}

	g.P("func (x *", msg.GoIdent, ") ", method, "() {")
	if !messageDisabled(msg) {
		seenOneofs := make(map[protoreflect.FullName]bool)
		for _, field := range msg.Fields {
			emitField(g, msg, field, seenOneofs)
		}
	}
	g.P("}")
	g.P()
}

func messageDisabled(msg *protogen.Message) bool {
	v, ok := getMessageBoolOption(msg, defaults.E_Disabled)
	return ok && v
}

func messageIgnored(msg *protogen.Message) bool {
	v, ok := getMessageBoolOption(msg, defaults.E_Ignored)
	return ok && v
}

func messageUnexported(msg *protogen.Message) bool {
	v, ok := getMessageBoolOption(msg, defaults.E_Unexported)
	return ok && v
}

func getMessageBoolOption(msg *protogen.Message, ext protoreflect.ExtensionType) (bool, bool) {
	opts := msg.Desc.Options()
	if opts == nil {
		return false, false
	}
	if !proto.HasExtension(opts, ext) {
		return false, false
	}
	v, ok := proto.GetExtension(opts, ext).(bool)
	if !ok {
		return false, false
	}
	return v, true
}

func fieldDefaults(field *protogen.Field) (*defaults.FieldDefaults, bool) {
	opts := field.Desc.Options()
	if opts == nil {
		return nil, false
	}
	if !proto.HasExtension(opts, defaults.E_Value) {
		return nil, false
	}
	v, ok := proto.GetExtension(opts, defaults.E_Value).(*defaults.FieldDefaults)
	if !ok || v == nil || v.Type == nil {
		return nil, false
	}
	return v, true
}

func oneofDefaultField(oo *protogen.Oneof) (string, bool) {
	opts := oo.Desc.Options()
	if opts == nil {
		return "", false
	}
	if !proto.HasExtension(opts, defaults.E_Oneof) {
		return "", false
	}
	v, ok := proto.GetExtension(opts, defaults.E_Oneof).(string)
	if !ok || v == "" {
		return "", false
	}
	return v, true
}
